#!/bin/sh
#
#  script to generate css from scss using sass
#
#
# generate css without line numbers
#
# --line_numbers
#
# expanded css, --style expanded
#
# sass --watch scss:css --style expanded
#
# generate css with line numbers
#
sass --watch scss:css --line-numbers --style expanded
#

